export const SET_PAGINATED_REQUEST_CLAIM_LIST = "SET_PAGINATED_REQUEST_CLAIM_LIST";
export const CHANGE_HANDLER_PROVIDER = "CHANGE_HANDLER_PROVIDER";
export const CLAIM_LIST_SWITCHED_TABLE_DATA_CHANGE = "CLAIM_LIST_SWITCHED_TABLE_DATA_CHANGE";
export const CLEAR_PROVIDER_LIST_DATA = "CLEAR_PROVIDER_LIST_DATA";