export const GET_CLAIMS = "GET_CLAIMS";
export const CLAIMS_LIST_TABLE_FILTERING = "CLAIMS_LIST_TABLE_FILTERING";
export const CLAIMS_LIST_TABLE_DATA_CHANGE = "CLAIMS_LIST_TABLE_DATA_CHANGE";

export const REGISTER_POLICIES = "REGISTER_POLICIES";
export const GET_SINGLE_POLICIES = "GET_SINGLE_POLICIES";
export const GET_POLICIES_INPUTS = "GET_POLICIES_INPUTS";
export const DELETE_POLICIES = "DELETE_POLICIES";
export const UPDATE_POLICIES = "UPDATE_POLICIES";
export const GET_CAR_COLORS = "GET_CAR_COLORS";
export const GET_POLICY_MAKE = "GET_POLICY_MAKE";
export const GET_PRODUCT_NAMES = "GET_PRODUCT_NAMES";
export const GET_PRODUCT_BENEFIT_COV = "GET_PRODUCT_BENEFIT_COV";
export const SET_USERS_LIST = "SET_USERS_LIST";
export const HANDLE_FIELD_CHANGE = "HANDLE_FIELD_CHANGE";
export const SET_POLICIES_LIST = "SET_POLICIES_LIST";
export const SET_CLAIMS_LIST = "SET_CLAIMS_LIST";
export const SET_CLAIMS_DETAILS = "SET_CLAIMS_DETAILS";
export const SET_ACTION_PERMISSIONS = "SET_ACTION_PERMISSIONS";
export const SET_USER_PROFILES_LIST = "SET_USER_PROFILES_LIST";
export const RESET_CLAIMS_DETAILS = "RESET_CLAIMS_DETAILS";
export const RESET_CLAIMS_LIST_AND_PAGINATION = "RESET_CLAIMS_LIST_AND_PAGINATION";


//Actions Claims
export const SET_REJECTION_REASONS = "SET_REJECTION_REASONS";
export const HANDLE_CHANGE_INPUT_STATUS = "HANDLE_CHANGE_INPUT_STATUS";
export const HANDLE_CHANGE_INPUT_SCHEDULE_CALL = "HANDLE_CHANGE_INPUT_SCHEDULE_CALL";
export const HANDLE_CHANGE_INPUT_LEAVE_MESSAGE = "HANDLE_CHANGE_INPUT_LEAVE_MESSAGE";
export const GET_ASSIGN_PROVIDER_REQUEST = "GET_ASSIGN_PROVIDER_REQUEST";
export const SET_INPUT_VALUES_ASSIGN_PROVIDER_SCREEN = "SET_INPUT_VALUES_ASSIGN_PROVIDER_SCREEN";
export const CHANGE_HANDLER_ASSIGN_PROVIDER = "CHANGE_HANDLER_ASSIGN_PROVIDER";
export const GET_ASSIGN_PROVIDER = "GET_ASSIGN_PROVIDER";
