export const SET_PAGINATED_REQUEST = "SET_PAGINATED_REQUEST";
export const CHANGE_HANDLER_PROVIDER = "CHANGE_HANDLER_PROVIDER";
export const PROVIDERS_LIST_TABLE_DATA_CHANGE = "PROVIDERS_LIST_TABLE_DATA_CHANGE";
export const CLEAR_PROVIDER_LIST_DATA = "CLEAR_PROVIDER_LIST_DATA";