export const SET_PAGINATED_REQUEST = "SET_PAGINATED_REQUEST";
export const SET_PAGINATED_REQUEST_AGENCY = "SET_PAGINATED_REQUEST_AGENCY";
export const SET_PAGINATED_REQUEST_GARAGE = "SET_PAGINATED_REQUEST_GARAGE";
export const SET_PAGINATED_REQUEST_SURVEYOR = "SET_PAGINATED_REQUEST_SURVEYOR";
export const CHANGE_HANDLER_PROVIDER = "CHANGE_HANDLER_PROVIDER";
export const PROVIDERS_LIST_TABLE_DATA_CHANGE = "PROVIDERS_LIST_TABLE_DATA_CHANGE";
export const CLEAR_PROVIDER_LIST_DATA = "CLEAR_PROVIDER_LIST_DATA";