export const GET_CLAIMS = "GET_CLAIMS";
export const CLAIMS_LIST_TABLE_FILTERING = "CLAIMS_LIST_TABLE_FILTERING";
export const CLAIMS_LIST_TABLE_DATA_CHANGE = "CLAIMS_LIST_TABLE_DATA_CHANGE";

export const REGISTER_POLICIES = "REGISTER_POLICIES";
export const GET_SINGLE_POLICIES = "GET_SINGLE_POLICIES";
export const GET_POLICIES_INPUTS = "GET_POLICIES_INPUTS";
export const DELETE_POLICIES = "DELETE_POLICIES";
export const UPDATE_POLICIES = "UPDATE_POLICIES";
export const GET_CAR_COLORS = "GET_CAR_COLORS";
export const GET_POLICY_MAKE = "GET_POLICY_MAKE";
export const GET_PRODUCT_NAMES = "GET_PRODUCT_NAMES";
export const GET_PRODUCT_BENEFIT_COV = "GET_PRODUCT_BENEFIT_COV";