export const CHANGE_HANDLER_NOTIFICATIONS = 'CHANGE_HANDLER_NOTIFICATIONS';
export const GET_REQUEST_NOTIFICATIONS = 'GET_REQUEST_NOTIFICATIONS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const SET_INPUT_VALUES_NOTIFICATIONS_SCREEN = 'SET_INPUT_VALUES_NOTIFICATIONS_SCREEN';

