//Provider Screen Types
export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_INPUT_VALUES_PROVIDER_TAB1_SCREEN = "SET_INPUT_VALUES_PROVIDER_TAB1_SCREEN";
export const ADD_CONTACTS = "ADD_CONTACTS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const EDIT_CONTACT_INDEX = "EDIT_CONTACT_INDEX";