//Root Getters
export const GET_GARAGES = "GET_GARAGES";
export const GET_CAR_AGENCIES = "GET_CAR_AGENCIES";
export const GET_AGENCIES = "GET_AGENCIES";
export const GET_SURVEYORERS = "GET_SURVEYORERS";



//Request
export const GET_REQUEST = "GET_REQUEST";




// Add Provider Getters
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_CITIES = 'GET_CITIES';
export const GET_AREAS = 'GET_AREAS';
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_CHILDS = "GET_SERVICES_CHILDS";




//Provider Screen Types
export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_INPUT_VALUES_PROVIDER_TAB1_SCREEN = "SET_INPUT_VALUES_PROVIDER_TAB1_SCREEN";
export const ADD_CONTACTS = "ADD_CONTACTS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const EDIT_CONTACT_INDEX = "EDIT_CONTACT_INDEX";



//Tab2

export const SET_INPUT_VALUES_PROVIDER_TAB2_SCREEN = "SET_INPUT_VALUES_PROVIDER_TAB2_SCREEN";
export const SAVE_SERVICE = "SAVE_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const EDIT_SERVICE_INDEX = "EDIT_SERVICE_INDEX";



//Tab3
export const SET_INPUT_VALUES_PROVIDER_TAB3_SCREEN = "SET_INPUT_VALUES_PROVIDER_TAB3_SCREEN";
export const SAVE_LOCATION = "SAVE_LOCATION";
export const EDIT_LOCATION_INDEX = "EDIT_LOCATION_INDEX";
export const DELETE_LOCATION = "DELETE_LOCATION";



//Clear State
export const CLEAR_ADD_PROVIDER_STATE = "CLEAR_ADD_PROVIDER_STATE";


//Save Provider
export const SAVE_PROVIDER_REQUEST = "SAVE_PROVIDER_REQUEST";
export const SAVE_PROVIDER = "SAVE_PROVIDER";



//SET Provider Details
export const SET_PROVIDER_DETAILS = "SET_PROVIDER_DETAILS";
export const SET_PROVIDER_DETAILS_REQUEST = "SET_PROVIDER_DETAILS_REQUEST";