
//Request
export const GET_REQUEST_RULES = "GET_REQUEST_RULES";
export const SET_INPUT_VALUES_RULES_SCREEN = "SET_INPUT_VALUES_RULES_SCREEN";
export const CHANGE_HANDLER_RULES = "CHANGE_HANDLER_RULES";

//Root Getters
export const GET_INIT_RULE_MAKES = "GET_INIT_RULE_MAKES";
export const GET_INIT_RULE_MODELS = "GET_INIT_RULE_MODELS";
export const GET_INIT_RULE_PRODUCTS = "GET_INIT_RULE_PRODUCTS";
export const GET_INIT_RULE_USERS = "GET_INIT_RULE_USERS";


// Add Getters
export const GET_INITIAL = 'GET_INITIAL';
export const GET_AFTER = 'GET_AFTER';

//Change Tab
export const CHANGE_TAB = "CHANGE_TAB";

//Add Rule
export const CLEAR_ADD_RULE_STATE = "CLEAR_ADD_RULE_STATE";
export const HANDLE_CHANGE_RULES = "HANDLE_CHANGE_RULES";