// For Smtp
export const GET_ALL_TIMEZONES = "GET_ALL_TIMEZONES"
export const GET_SMTP_CONFIG = "GET_SMTP_CONFIG"
export const HANDLE_SMTP_VALUES = "HANDLE_SMTP_VALUES"
export const NAVIGATE_SMTP_BACK = "NAVIGATE_SMTP_BACK"

// For Email Signature
export const GET_EMAIL_CONFIG = "GET_EMAIL_CONFIG"
export const NAVIGATE_EMAIL_BACK = "NAVIGATE_EMAIL_BACK"
export const HANDLE_EMAIL_VALUES = "HANDLE_EMAIL_VALUES"

// For Account
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"
export const GET_ACCOUNT_CONFIG = "GET_ACCOUNT_CONFIG"
export const NAVIGATE_ACCOUNT_BACK = "NAVIGATE_ACCOUNT_BACK"
export const HANDLE_ACCOUNT_VALUES = "HANDLE_ACCOUNT_VALUES"
export const HANDLE_ACCOUNT_VALUES_OUTER = "HANDLE_ACCOUNT_VALUES_OUTER"
export const RESET_ACCOUNT_STATE = "RESET_ACCOUNT_STATE"
export const GET_ALL_ACTIVITY_LOGS = "GET_ALL_ACTIVITY_LOGS"
export const GET_ALL_ACTIVITY_BY_ID = "GET_ALL_ACTIVITY_BY_ID"