// For Smtp
export const GET_ALL_TIMEZONES = "GET_ALL_TIMEZONES"
export const GET_SMTP_CONFIG = "GET_SMTP_CONFIG"
export const HANDLE_SMTP_VALUES = "HANDLE_SMTP_VALUES"
export const NAVIGATE_SMTP_BACK = "NAVIGATE_SMTP_BACK"

// For Email Signature
export const GET_EMAIL_CONFIG = "GET_EMAIL_CONFIG"
export const NAVIGATE_EMAIL_BACK = "NAVIGATE_EMAIL_BACK"
export const HANDLE_EMAIL_VALUES = "HANDLE_EMAIL_VALUES"