export const SET_TASKS_BY_DND = "SET_TASKS_BY_DND";
export const GET_MY_TASKS_REQUEST = "GET_MY_TASKS_REQUEST";
export const GET_MY_TASKS = "SET_MY_TASKS";


export const GET_PENDING_TASKS_REQUEST = "GET_PENDING_TASKS_REQUEST";
export const GET_PENDING_TASKS = "GET_PENDING_TASKS";
