// Auth
export const SET_TOKEN = 'SET_TOKEN';
export const REGISTER_USER = 'REGISTER_USER';

// Product
export const REGISTER_PRODUCT = "REGISTER_PRODUCT,"
export const REGISTER_BENEFIT = "REGISTER_BENEFIT,"
export const GET_PRODUCTS = "GET_PRODUCTS,"
export const GET_PRODUCT_TYPE = "GET_PRODUCT_TYPE,"
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT,"
export const GET_PRODUCT_INPUTS = "GET_PRODUCT_INPUTS,"
export const DIT_PRODUCT_TYPE = "DIT_PRODUCT_TYPE,"
export const EDIT_PRODUCT = "EDIT_PRODUCT,"
export const DELETE_PRODUCT = "DELETE_PRODUCT,"
export const DELETE_PRODUCT_TYPE = "DELETE_PRODUCT_TYPE,"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT,"
export const UPDATE_PRODUCT_TYPE = "UPDATE_PRODUCT_TYPE,"










// export const GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST';
// export const UPDATE_USER_SEND_REQ = 'UPDATE_USER_SEND_REQ';
// export const UPDATE_USER_CENCEL_REQ = 'UPDATE_USER_CENCEL_REQ';
// export const UNFRIEND_REQ = 'UNFRIEND_REQ';

// export const LOGIN_ERROR = "LOGIN_ERROR";
// export const LOGIN_START = 'LOGIN_START';
// export const LOGIN_FAIL = ' LOGIN_FAIL';
// export const LOGOUT = ' LOGOUT';



