// Auth
export const SET_AUTH = 'SET_AUTH';
export const REGISTER_USER = 'REGISTER_USER';

// Product
export const REGISTER_PRODUCT = "REGISTER_PRODUCT,"
export const REGISTER_BENEFIT = "REGISTER_BENEFIT,"
export const GET_PRODUCTS = "GET_PRODUCTS,"
export const GET_PRODUCT_TYPE = "GET_PRODUCT_TYPE,"
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT,"
export const GET_PRODUCT_INPUTS = "GET_PRODUCT_INPUTS,"
export const DIT_PRODUCT_TYPE = "DIT_PRODUCT_TYPE,"
export const EDIT_PRODUCT_BENEFIT = "EDIT_PRODUCT_BENEFIT,"
export const CANCEL_PRODUCT_BENEFIT = "CANCEL_PRODUCT_BENEFIT,"
export const DELETE_PRODUCT = "DELETE_PRODUCT,"
export const DELETE_PRODUCT_BENEFIT = "DELETE_PRODUCT_BENEFIT,"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT,"
export const UPDATE_PRODUCT_BENEFIT = "UPDATE_PRODUCT_BENEFIT,"
export const CHECK_PRODUCT_ACTIVE = "CHECK_PRODUCT_ACTIVE"
export const PRODUCT_SORT = "PRODUCT_SORT"
export const FILTERS_DATA_CHANGE = "FILTERS_DATA_CHANGE"
export const HANDLE_PRODUCT_FILTERING = "HANDLE_PRODUCT_FILTERING"
export const SET_PRODUCTS_PAGE_INDEX = "SET_PRODUCTS_PAGE_INDEX"


// Policy

export const REGISTER_POLICIES = "REGISTER_POLICIES"
export const GET_POLICIES = "GET_POLICIES"
export const GET_SINGLE_POLICIES = "GET_SINGLE_POLICIES"
export const GET_POLICIES_INPUTS = "GET_POLICIES_INPUTS"
export const DELETE_POLICIES = "DELETE_POLICIES"
export const UPDATE_POLICIES = "UPDATE_POLICIES"
export const GET_CAR_COLORS = "GET_CAR_COLORS"
export const GET_POLICY_MAKE = "GET_POLICY_MAKE"
export const GET_PRODUCT_NAMES = "GET_PRODUCT_NAMES"
export const GET_PRODUCT_BENEFIT_COV = "GET_PRODUCT_BENEFIT_COV"









// export const GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST';
// export const UPDATE_USER_SEND_REQ = 'UPDATE_USER_SEND_REQ';
// export const UPDATE_USER_CENCEL_REQ = 'UPDATE_USER_CENCEL_REQ';
// export const UNFRIEND_REQ = 'UNFRIEND_REQ';

// export const LOGIN_ERROR = "LOGIN_ERROR";
// export const LOGIN_START = 'LOGIN_START';
// export const LOGIN_FAIL = ' LOGIN_FAIL';
// export const LOGOUT = ' LOGOUT';



