//User Screen Types
export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_INPUT_VALUES_USER_SCREEN = "SET_INPUT_VALUES_USER_SCREEN";
export const CLEAR_INPUT_VALUES_USER_SCREEN = "CLEAR_INPUT_VALUES_USER_SCREEN";
export const SET_INPUT_VALUES_ACCESS_GROUP_SCREEN = "SET_INPUT_VALUES_ACCESS_GROUP_SCREEN";
export const SET_ROLES = "SET_ROLES";
export const SET_ACCESS_GROUPS = "SET_ACCESS_GROUPS";
export const SET_MODULES = "SET_MODULES";
export const SET_USERS = "SET_USERS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_USER_DETAILS_REQUEST = "SET_USER_DETAILS_REQUEST";
export const SET_USER_DELETE_REQUEST = "SET_USER_DELETE_REQUEST";
export const SET_USERS_REQUEST = "SET_USERS_REQUEST";
export const SET_USER_ADD_REQUEST = "SET_USER_ADD_REQUEST";
export const SET_USER_PAGE_INDEX = "SET_USER_PAGE_INDEX";
export const SET_ACTIONS = "SET_ACTIONS";
export const SET_MODULES_ACTIONS = "SET_MODULES_ACTIONS";
export const SET_ACCESS_GROUP_DETAILS_REQUEST = "SET_ACCESS_GROUP_DETAILS_REQUEST";
export const SET_ACCESS_GROUP_DETAILS = "SET_ACCESS_GROUP_DETAILS";
export const SET_GROUP_ADD_REQUEST = "SET_GROUP_ADD_REQUEST";
export const SET_GROUP_ADD = "SET_GROUP_ADD";
export const SET_GROUP_DELETE_REQUEST = "SET_GROUP_DELETE_REQUEST";



