//User Screen Types
export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_INPUT_VALUES_USER_SCREEN = "SET_INPUT_VALUES_USER_SCREEN";
export const CLEAR_INPUT_VALUES_USER_SCREEN = "CLEAR_INPUT_VALUES_USER_SCREEN";
export const SET_INPUT_VALUES_ACCESS_GROUP_SCREEN = "SET_INPUT_VALUES_ACCESS_GROUP_SCREEN";
export const SET_ROLES = "SET_ROLES";
export const SET_ACCESS_GROUPS = "SET_ACCESS_GROUPS";
export const SET_MODULES = "SET_MODULES";
export const SET_USERS = "SET_USERS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_USER_DETAILS_REQUEST = "SET_USER_DETAILS_REQUEST";




