//User Screen Types
export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_INPUT_VALUES_USER_SCREEN = "SET_INPUT_VALUES_USER_SCREEN";
export const CLEAR_INPUT_VALUES_USER_SCREEN = "CLEAR_INPUT_VALUES_USER_SCREEN";
export const SET_INPUT_VALUES_ACCESS_GROUP_SCREEN = "SET_INPUT_VALUES_ACCESS_GROUP_SCREEN"
