export const LOAD_VEHICLE_PARTS_LIST = 'LOAD_VEHICLE_PARTS_LIST';
export const ADD_VEHICLE_PART = 'ADD_VEHICLE_PART';
export const UPDATE_VEHICLE_PART = 'UPDATE_VEHICLE_PART';
export const DELETE_VEHICLE_PART = 'DELETE_VEHICLE_PART';