export const LOAD_VEHICLE_PARTS_LIST = 'LOAD_VEHICLE_PARTS_LIST';
export const LOAD_VEHICLE_PART = 'LOAD_VEHICLE_PART';
export const UPDATE_VEHICLE_PART = 'UPDATE_VEHICLE_PART';
export const DELETE_VEHICLE_PART = 'DELETE_VEHICLE_PART';
export const HANDLE_VEHICLE_PART_VALUES_CHANGE = 'HANDLE_VEHICLE_PART_VALUES_CHANGE';
export const CLEAR_VEHICLE_PART_VALUES_CHANGE = 'CLEAR_VEHICLE_PART_VALUES_CHANGE';
export const ADD_VEHICLE_PART = 'ADD_VEHICLE_PART';